comment:
  layout: header, changes, diff, sunburst
coverage:
  fixes:
  - ::src/
  ignore:
  - src/Shapeshifter\.Tests/.*
  - .*\.xaml\.cs
  - .*\.xaml
  - .*\.Designer\.cs
  - .*/Api/\w+Api\.cs
  - .*/Designer/.*
  - .*/Controls/.*
  status:
    patch:
      default:
        target: '0'
    project:
      default:
        target: auto
